### ISSUE TITLE
Problem with plasmoids

### ISSUE THREAD

**Issue by AlexD97** [dos1/kded_rotation#1]
I don't know if it is an issue with your script or with plasma, but after a rotation my plasmoid are messied up.

**Comment by dos1** [comment]
Definitely Plasma :)

**Comment by dadosch** [comment]
@AlexD97 did you find a solution to this/ reported a bug to Plasma?

**Comment by AlexD97** [comment]
Unfortunately I didn't find a solution. I also didn't report a bug.

**Comment by dadosch** [comment]
> Unfortunately I didn't find a solution. I also didn't report a bug.

I found a "workaround": If I place my plasmoids only on the lower half of the screen, they don't get tossed around when turning back to normal again.
