### ISSUE TITLE
Feature request for further actions on rotation

### ISSUE THREAD

**Issue by timdj** [dos1/kded_rotation#14]
It would be nice if this tool could also call an external command on rotation (even different ones per direction) or integrate the following features:

I use this on a 2-1 tablet so when I fold my screen  (and rotate) I manually call a script to disable the keyboard and mouse using
```
xinput float 16
xinput float 11
```
I also start onboard

When rotating back I close onboard and reattach the input devices.

What would be also very handy is if this rotate script would also automatically change the font subhinting in the right direction

**Comment by parkerlreed** [comment]
You can do this easily. Everything is in the helper script.

Add the actions you want to each if section

https://github.com/dos1/kded_rotation/blob/master/orientation-helper#L40

**Comment by timdj** [comment]
I did this. Thank you!
