### ISSUE TITLE
screen rotation broken on resume from suspend

### ISSUE THREAD

**Issue by k4ever** [dos1/kded_rotation#17]
Is there a way to make kded_rotation work after suspend? I'm on a Surface Pro 4 running KDE Neon 18.04, Plasma 5.18.0. KDED_Rotation works fine on startup, but breaks on suspend. The only way I have found to get it to work again is to reboot. I need this to work with suspend..

**Comment by dos1** [comment]
That would be a kernel issue.

**Comment by k4ever** [comment]
Ok, I'm a little confused. If this is kernel issue, what am I supposed to do? Is there a particular kernel that works well with this? Is there a grub boot parameter I need to add? Is there a kernel driver that needs to be loaded/unloaded before/after suspend? I can't imagine that anyone who has this installed on there laptop doesn't put their device into suspend at some point.

**Comment by dos1** [comment]
I'd start with reporting the issue: https://www.kernel.org/doc/html/latest/admin-guide/reporting-bugs.html
