### ISSUE TITLE
Rotation is off by 90 degrees on Yoga 11e

### ISSUE THREAD

**Issue by GregJPreece** [dos1/kded_rotation#18]
Operating System: Kubuntu 19.10
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.12.4
Kernel Version: 5.3.0-40-generic
OS Type: 64-bit

Awesome to see this module existing, however I'm having some issues with it on my Lenovo Yoga 11e. The autorotation kicks in on login as expected, and does rotate the screen, but always rotates it 90 degrees anticlockwise from what is expected. For example, when I am in the traditional laptop configuration, the "bottom" of the KDE screen is the screen's physical right edge. If I physically rotate the screen to match, the KDE screen rotates so that the "bottom" is on the screen's physical top edge, and so on.

If I use `/usr/bin/orientation-helper --rotation normal` to override the listener, the KDE screen rotates back to a standard laptop configuration, so the orientation helper script is clearly setting the rotation correctly. It seems that the data coming from the rotation sensor does not match what exists - possibly down to the orientation of the sensor?

Looking at the code, this may be a bug in `QOrientationSensor` but I can't be 100% certain. For now I'll write a little hack into the code myself and recompile, should work around the issue.

**Comment by GregJPreece** [comment]
I was able to get the screen rotation properly using a quick hack:

```
void ScreenRotator::updateOrientation() {
        if (!sensor->reading()) return;
        currentOrientation = sensor->reading()->orientation();
        QString o;
        switch (currentOrientation) {
                case QOrientationReading::TopUp:
//                      o = "normal";
                        o = "right-up";
                        break;
                case QOrientationReading::TopDown:
//                      o = "bottom-up";
                        o = "left-up";
                        break;
                case QOrientationReading::LeftUp:
//                      o = "left-up";
                        o = "normal";
                        break;
                case QOrientationReading::RightUp:
//                      o = "right-up";
                        o = "bottom-up";
                        break;
                default:
                        o = "none";
                        return;
        }

        helper.start("orientation-helper", {"-r", o});

}
```

**Comment by dos1** [comment]
Sounds like you need to specify a mount matrix for the sensor in udev database, so iio-sensor-proxy can correctly deduce the orientation.

See https://github.com/systemd/systemd/pull/7174 - it's matching "3rd Gen" only, so if you have a different generation you'll likely have to add an identifier that matches your hardware.

Closing since it's unrelated to kded_rotation.
