### ISSUE TITLE
Timer works, but nothing else

### ISSUE THREAD

**Issue by padmesigma** [dos1/kded_rotation#19]
I'm trying to set this up on a brand new install of Manjaro KDE Plasma on a Lenovo X1 Yoga Gen 4, since this seemed to be the most recommended screen rotator for this laptop. I've gotten it installed and running, however although the timer shows up properly when the rotation is changed, the screen remains in the same position and never turns. I'd appreciate any advice?

**Comment by Justinzobel** [comment]
Check to see that /usr/bin/orientation-helper is executable (+x). I had the same issue.

**Comment by dos1** [comment]
Closing since seems it was just missing executable permissions.
