### ISSUE TITLE
Black screen for a second

### ISSUE THREAD

**Issue by danielzgtg** [dos1/kded_rotation#23]
The black screen duration during the screen orientation change is a bit long.

When I physically rotate my device and let kded_rotation auto-rotate, I see a black screen for ~1 second. This is long in comparison to the ½ second black screen when I change the rotation in KDE system settings.

This is a problem because seeing the black screen for that long is a worse user experience than Android and Windows, which do something about it like showing an animation in the middle.

**Comment by dos1** [comment]
kded_rotation simply uses `xrandr` to rotate the screen. It has no influence over how the rotation actually happens.
