### ISSUE TITLE
How to disable this in laptop mode?

### ISSUE THREAD

**Issue by jclsn** [dos1/kded_rotation#29]
Do you have an idea how to easily disable and enable the rotation? I tried disabling iio:device0 with tablet-mode, but that doesn't work. If you stop the iio-sensor-proxy, you have to reboot to enable it again.

**Comment by danielzgtg** [comment]
Try editing `orientation_helper`. Add an `exit` at the top inside a `if` statement. This workaround will disable the rotation but not the notification. What command detects your "laptop mode"?

**Comment by jclsn** [comment]
I don't have the laptop anymore, but thanks

**Comment by quantenProjects** [comment]
Just for convenience, if somebody else also search for a solution: Have a look into the forks of this project. Some implemented a locking mode. Some in the helper, some in the service itself.

I use a simple patch and two `.desktop` entries, to control the behavior:

Patch the `orientation-helper` with this patch:

```patch
--- orientation-helper  2023-09-09 11:33:23.971990822 +0200
+++ /usr/bin/orientation-helper 2023-09-09 11:37:46.957005384 +0200
@@ -33,6 +33,11 @@
   shift
 done
 
+if [ -f "/run/user/1000/no-rotation" ]; then
+       echo "no-rotation exists, exit"
+       exit
+fi
+
 if [ -z "$ROTATION" ]; then
   usage
 fi
```

`enable-rotation.desktop`

```
[Desktop Entry]
Exec=/usr/bin/rm /run/user/1000/no-rotation
Icon=rotation-allowed-symbolic
Name=Enable Rotation
NoDisplay=false
Path=
StartupNotify=true
Terminal=false
Type=Application
```

`disable-rotation.desktop`

```
[Desktop Entry]
Exec=/usr/bin/touch /run/user/1000/no-rotation
Icon=rotation-locked-landscape-symbolic
Name=Disable Rotation
NoDisplay=false
Path=
StartupNotify=true
Terminal=false
Type=Application
```

Install both `.desktop` with `desktop-file-install`.

Note that this solution activates the rotation by default with each reboot.
