### ISSUE TITLE
kded rotation service detect wrong orientation on my machine.

### ISSUE THREAD

**Issue by BruceZhang1993** [dos1/kded_rotation#3]
When i start kde rotation service with normal orientation, service detects as top-left, and screen goes to top-left.
Then i stop service, and running `orientation-helper normal`make screen normal again.

**Comment by dos1** [comment]
kded_rotation uses QOrientationSensor, which in turn uses iio-sensor-proxy to get rotation data, so you should report it to iio-sensor-proxy (and you should probably put way more information about your hardware there if you want your report to be actually useful).
